
%macro B2C_Consolidar_Tabelas;

%mensagem(1. Gera Tabela RECUPERA_OPERACAO);
DATA RECUPERA_OPERACAO_DIARIO;
SET 
	TT.OPERACAO_&safra_final2. (&COLUMN3_B2C.)
	TT.OPERACAO_&safra_final1. (&COLUMN3_B2C.)
	;
	SAFRA = (YEAR(data_base)*100) + MONTH(data_base);
	DIA = DAY(data_base);
	MES = MONTH(data_base);

	IF flag_categoria_b_passivel = 1 THEN CLASS = 'PASSIVEL';
	ELSE IF flag_categoria_b_previa = 1 THEN CLASS = 'PREVIA';
	ELSE CLASS = 'NULL';

	FORMAT DIVIDA_ANTES 	8.2;
	FORMAT DIVIDA_DEPOIS	8.2;

	DIVIDA_ANTES = 	
	COALESCE(divida_CATEGORIA_A_SISTEMA_A,0) + 
	COALESCE(divida_CATEGORIA_B_SISTEMA_A,0) + 
	COALESCE(divida_CATEGORIA_B_SISTEMA_B,0) + 
	COALESCE(divida_CATEGORIA_C_SISTEMA_A,0) + 
	COALESCE(divida_CATEGORIA_C_SISTEMA_C,0);

	DIVIDA_DEPOIS = 
	COALESCE(divida_apos_CATEGORIA_A_SISTEMA_A,0) +
	COALESCE(divida_apos_CATEGORIA_B_SISTEMA_A,0) + 
	COALESCE(divida_apos_CATEGORIA_B_SISTEMA_B,0) + 
	COALESCE(divida_apos_CATEGORIA_C_SISTEMA_A,0) + 
	COALESCE(divida_apos_CATEGORIA_C_SISTEMA_C,0); 

	ACORDOS = 
	MAX(
	COALESCE(fl_acordo_sistema_c,0), 
	COALESCE(fl_acordo_sistema_b,0), 
	COALESCE(fl_acordo_sistema_a_s_log,0), 
	COALESCE(fl_acordo_sistema_a,0)
	);

	QUEBRAS = 
	MAX(
	COALESCE(fl_quebra_acordo_sisA_catA,0) , 
	COALESCE(fl_quebra_acordo_sisA_catB,0) , 
	COALESCE(fl_quebra_acordo_sisA_catC,0) ,
	COALESCE(fl_quebra_acordo_sistema_c,0) , 
	COALESCE(fl_quebra_acordo_sistema_b,0) ,
	COALESCE(fl_quebra_acordo_sisA_catA_s_log,0) ,
	COALESCE(fl_quebra_acordo_sisA_catB_s_log,0) ,
	COALESCE(fl_quebra_acordo_sisA_catC_s_log,0)
	);

	aging_max_apos_total =  	
	COALESCE(aging_max_apos_CATEGORIA_A_AMDOC,0) + 
	COALESCE(aging_max_apos_CATEGORIA_B_SISTEMA_A,0) +
	COALESCE(aging_max_apos_CATEGORIA_B_SISTEMA_B,0) + 
	COALESCE(aging_max_apos_CATEGORIA_C_SISTEMA_A,0) + 	
	COALESCE(aging_max_apos_CATEGORIA_C_SISTEMA_C,0);
	
	aging_max_total =  	
	COALESCE(aging_max_CATEGORIA_A_SISTEMA_A,0) + 	
	COALESCE(aging_max_CATEGORIA_B_SISTEMA_A,0) + 
	COALESCE(aging_max_CATEGORIA_B_SISTEMA_B,0) +
	COALESCE(aging_max_CATEGORIA_C_SISTEMA_A,0) + 
	COALESCE(aging_max_CATEGORIA_C_SISTEMA_C,0);
	
	aging = max(
	COALESCE(aging_max_CATEGORIA_A_SISTEMA_A,0),
	COALESCE(aging_max_CATEGORIA_B_SISTEMA_A,0),
	COALESCE(aging_max_CATEGORIA_B_SISTEMA_B,0),
	COALESCE(aging_max_CATEGORIA_C_SISTEMA_A,0),
	COALESCE(aging_max_CATEGORIA_C_SISTEMA_C,0)
	);
RUN;

%mensagem(2. Aplica regras a TB RECUPERA_OPERACAO);
DATA RECUPERA_OPERACAO_DIARIO;
SET RECUPERA_OPERACAO_DIARIO;

	IF (
	COALESCE(divida_CATEGORIA_A_SISTEMA_A,0) + 
	COALESCE(divida_CATEGORIA_B_SISTEMA_A,0) + 
	COALESCE(divida_CATEGORIA_B_SISTEMA_B,0) + 
	COALESCE(divida_CATEGORIA_C_SISTEMA_A,0) + 		
	COALESCE(divida_CATEGORIA_C_SISTEMA_C,0)
	) 
	NE 0 THEN POSSUI_DIVIDA = 1; ELSE POSSUI_DIVIDA = 0;

	IF COALESCE(aging_max_apos_total,0) < COALESCE(aging_max_total,0) 
	AND DIVIDA_DEPOIS < DIVIDA_ANTES 
	AND DIVIDA_DEPOIS NE 0 
	AND DIVIDA_ANTES NE 0
	THEN AGING_REDUZIDO = 1; ELSE AGING_REDUZIDO = 0;

	IF DIVIDA_ANTES > DIVIDA_DEPOIS	
	AND DIVIDA_DEPOIS NE 0 
	AND COALESCE(aging_max_apos_total,0) >= COALESCE(aging_max_total,0) 
	THEN DIVIDA_REDUZIDA = 1; ELSE DIVIDA_REDUZIDA = 0;
	
	IF DIVIDA_ANTES NE 0 
	AND DIVIDA_ANTES > DIVIDA_DEPOIS 
	AND COALESCE(aging_max_apos_total,0) < COALESCE(aging_max_total,0)
	THEN DIVIDA_PAGA = 1; ELSE DIVIDA_PAGA = 0;

	IF DIVIDA_ANTES NE 0 
	AND DIVIDA_ANTES <= DIVIDA_DEPOIS 
	AND COALESCE(aging_max_apos_total,0) > COALESCE(aging_max_total,0)
	THEN DIVIDA_NAO_PAGA = 1; ELSE DIVIDA_NAO_PAGA = 0;
	
	IF POSSUI_DIVIDA = 0 THEN ACORDOS = 0; ELSE ACORDOS = ACORDOS;
	
	DCONCATENADO =  CATX('',SAFRA,GRUPO_ATENDIMENTO,DIA);
	MCONCATENADO =  CATX('',SAFRA,GRUPO_ATENDIMENTO);
	
	IF 		0	<=aging	<10 	then CARTEIRA_ENTRADA = 'M0';
	ELSE IF 10	<=aging	<31 	then CARTEIRA_ENTRADA = 'M1';
	ELSE IF 31	<=aging	<51 	then CARTEIRA_ENTRADA = 'M2';
	ELSE IF 51	<=aging	<91 	then CARTEIRA_ENTRADA = 'M3';
	ELSE IF 91	<=aging	<121 	then CARTEIRA_ENTRADA = 'M4';
	ELSE IF 121	<=aging	<271 	then CARTEIRA_ENTRADA = 'F0';
	ELSE IF 271	<=aging	<361 	then CARTEIRA_ENTRADA = 'F1';
	ELSE IF 361	<=aging	<721 	then CARTEIRA_ENTRADA = 'F2';
	ELSE IF 721	<=aging	<1081 	then CARTEIRA_ENTRADA = 'F3';
	ELSE IF 1081<=aging	<1441 	then CARTEIRA_ENTRADA = 'F4';
	ELSE IF 1441<=aging	<1801 	then CARTEIRA_ENTRADA = 'F5';
	ELSE IF 1801<=aging	<2161 	then CARTEIRA_ENTRADA = 'F6';
	ELSE IF 2161<=aging	<2521 	then CARTEIRA_ENTRADA = 'F7';
	ELSE IF 2521<=aging	<2881 	then CARTEIRA_ENTRADA = 'F8';
	ELSE IF 2881<=aging	<3241 	then CARTEIRA_ENTRADA = 'F9';
	ELSE IF 3241<=aging 		then CARTEIRA_ENTRADA = 'F10';
	ELSE CARTEIRA_ENTRADA = 'NAO ENCONTRADO';
	
	IF DIVIDA_REDUZIDA = 1 THEN DIVIDA_ANTES_S_RED = 0;
	ELSE DIVIDA_ANTES_S_RED = DIVIDA_ANTES;
	
	IF DIVIDA_REDUZIDA = 1 THEN DIVIDA_DEPOIS_S_RED = 0;
	ELSE DIVIDA_DEPOIS_S_RED = DIVIDA_DEPOIS;
RUN;

DATA OPERACAO_DIARIO;
SET WORK.OPERACAO_DIARIO(&COLMNFIN_B2C.);


%mensagem(3. Ordena Tabela e gera Tabela Unique);
PROC SORT DATA= RECUPERA_OPERACAO_DIARIO; BY DOCUMENTO descending data_base DESCENDING DIVIDA_PAGA DESCENDING DIVIDA_REDUZIDA;
PROC SORT DATA= RECUPERA_OPERACAO_DIARIO Out=RECUPERA_OPERACAO_DIARIO_UNI Nodupkey; BY DOCUMENTO GRUPO_ATENDIMENTO SAFRA;

%mend;

%macro B2C_Aplica_regra_Unique_Diario;

%mensagem(3.1. Aplica regra de Diario - Unique);

%mensagem(3.1.1 Cria regra de maturacao);
PROC SQL;
CREATE TABLE RECUPERA_OP_DIA_MATU_UNIQUE AS 
SELECT *
,CASE 
	WHEN data_base <= (SELECT MAX(data_base)-13 FROM RECUPERA_OPERACAO_DIARIO_UNI) 
	THEN "SIM" ELSE "NÃO" END AS MATURADO 
FROM (
	SELECT * FROM RECUPERA_OPERACAO_DIARIO_UNI 
	WHERE data_base <= (SELECT MAX(data_base)
						FROM RECUPERA_OPERACAO_DIARIO_UNI WHERE DIVIDA_DEPOIS > 0)) AS A 
ORDER BY data_base
;QUIT;

%mensagem(3.1.2 Gera tabela auxiliar);
PROC SQL;
CREATE TABLE AUXILIAR_DIARIO_UNIQUE AS 
SELECT 
SAFRA 
,DCONCATENADO
,USERNAME 
,SUM(POSSUI_DIVIDA) AS POSSUI_DIVIDA
,SUM(DIVIDA_PAGA) / SUM(POSSUI_DIVIDA) AS PERC_DIV
FROM RECUPERA_OP_DIA_MATU_UNIQUE A 
GROUP BY 1,2,3
;QUIT;

%mensagem(3.1.3 Ordena tabela auxiliar);
PROC SORT DATA= AUXILIAR_DIARIO_UNIQUE; BY DCONCATENADO DESCENDING PERC_DIV;

%mensagem(3.1.4 Aplica regra de posicao);
DATA AUXILIAR_DIARIO_UNIQUE;
SET AUXILIAR_DIARIO_UNIQUE;
BY DCONCATENADO;
IF first.DCONCATENADO then Posicao = 1;
ELSE Posicao + 1;
RUN;

%mensagem(3.1.5 Gera tabela auxiliar TAS);
PROC SQL;
CREATE TABLE TAS_DIARIO_UNIQUE AS 
SELECT 
SAFRA 
,DCONCATENADO
,USERNAME
,CATX('',USERNAME,DCONCATENADO) AS ID
,POSSUI_DIVIDA
,Posicao	
,(Posicao/(SELECT QTD 
			FROM (
				SELECT DCONCATENADO ,COUNT(DCONCATENADO) AS QTD 
				FROM AUXILIAR_DIARIO_UNIQUE GROUP BY 1) AS B 
			WHERE A.DCONCATENADO = B.DCONCATENADO)) AS Percentual
FROM AUXILIAR_DIARIO_UNIQUE A
;QUIT;

%mend;
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

%macro B2C_Aplica_regra_Esforco_Diario;

%mensagem(3.2. Aplica regra de Diario - Esforco);

%mensagem(3.2.1 Cria regra de maturacao);
PROC SQL;
CREATE TABLE RECUPERA_OP_DIA_MATU AS 
SELECT *
,CASE 
	WHEN data_base <= (SELECT MAX(data_base)-13 FROM RECUPERA_OPERACAO_DIARIO) 
	THEN "SIM" ELSE "NÃO" END AS MATURADO 
FROM (
	SELECT * FROM RECUPERA_OPERACAO_DIARIO 
	WHERE data_base <= (SELECT MAX(data_base) 
						FROM RECUPERA_OPERACAO_DIARIO WHERE DIVIDA_DEPOIS > 0)) AS A 
ORDER BY data_base
;QUIT;

%mensagem(3.2.2 Cria tabela Auxiliar);
PROC SQL;
CREATE TABLE AUXILIAR_DIARIO AS 
SELECT 
SAFRA 
,DCONCATENADO
,USERNAME 
,SUM(POSSUI_DIVIDA) AS POSSUI_DIVIDA
,SUM(DIVIDA_PAGA) / SUM(POSSUI_DIVIDA) AS PERC_DIV
FROM RECUPERA_OP_DIA_MATU A 
GROUP BY 1,2,3
;QUIT;

%mensagem(3.2.3 ordena tabela Auxiliar);
PROC SORT DATA= AUXILIAR_DIARIO; BY DCONCATENADO DESCENDING PERC_DIV;

%mensagem(3.2.4 Aplica regra de posicao);
DATA AUXILIAR_DIARIO;
SET AUXILIAR_DIARIO;
BY DCONCATENADO;
IF first.DCONCATENADO then Posicao = 1;
ELSE Posicao + 1;
RUN;

%mensagem(3.2.5 Cria tabela auxiliar TAS);
PROC SQL;
CREATE TABLE TAS_DIARIO AS 
SELECT 
SAFRA 
, DCONCATENADO
, USERNAME
, CATX('',USERNAME,DCONCATENADO) AS ID
, POSSUI_DIVIDA
, Posicao	
,(Posicao/(SELECT QTD 
			FROM (
				SELECT DCONCATENADO ,COUNT(DCONCATENADO) AS QTD 
				FROM AUXILIAR_DIARIO GROUP BY 1) AS B 
			WHERE A.DCONCATENADO = B.DCONCATENADO)) AS Percentual
FROM AUXILIAR_DIARIO A
;QUIT;

%mend;

/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

%macro B2C_Aplica_Regra_Unique_Mensal;

%mensagem(4. Aplicacao para modelo Mensal);
DATA RECUPERA_OPERACAO_MENSAL;
SET RECUPERA_OPERACAO_DIARIO;

PROC SORT DATA= RECUPERA_OPERACAO_MENSAL; BY DOCUMENTO descending data_base DESCENDING DIVIDA_PAGA DESCENDING DIVIDA_REDUZIDA;
PROC SORT DATA= RECUPERA_OPERACAO_MENSAL Out=RECUPERA_OPERACAO_MENSAL_UNI Nodupkey; BY DOCUMENTO GRUPO_ATENDIMENTO SAFRA;

%mensagem(4.1. Aplicacao para modelo Mensal - Unique);
PROC SQL;
CREATE TABLE RECUPERA_OP_MEN_MATU_UNIQUE AS 
SELECT * 
,CASE 
	WHEN data_base <= (SELECT MAX(data_base)-14 FROM RECUPERA_OPERACAO_MENSAL_UNI) 
	THEN "SIM" ELSE "NÃO" END AS MATURADO 
FROM (
	SELECT * FROM RECUPERA_OPERACAO_MENSAL_UNI 
	WHERE data_base <= (SELECT MAX(data_base) 
						FROM RECUPERA_OPERACAO_MENSAL_UNI WHERE DIVIDA_DEPOIS > 0)) AS A 
ORDER BY data_base
;QUIT;

PROC SQL;
CREATE TABLE AUXILIAR_MENSAL_UNIQUE AS 
SELECT 
SAFRA 
,MCONCATENADO
,USERNAME 
,SUM(POSSUI_DIVIDA) AS POSSUI_DIVIDA
,SUM(DIVIDA_PAGA) / SUM(POSSUI_DIVIDA) AS PERC_DIV
FROM RECUPERA_OP_MEN_MATU_UNIQUE A 
GROUP BY 1,2,3
;QUIT;

PROC SORT DATA= AUXILIAR_MENSAL_UNIQUE; BY MCONCATENADO DESCENDING PERC_DIV;

DATA AUXILIAR_MENSAL_UNIQUE;
SET AUXILIAR_MENSAL_UNIQUE;
BY MCONCATENADO;
IF first.MCONCATENADO then Posicao = 1;
ELSE Posicao + 1;
RUN;

PROC SQL;
CREATE TABLE TAS_MENSAL_UNIQUE AS 
SELECT 
SAFRA 
, MCONCATENADO
, USERNAME
, CATX('',USERNAME,MCONCATENADO) AS ID
, POSSUI_DIVIDA
, Posicao	
,(Posicao/(SELECT QTD 
			FROM (
				SELECT MCONCATENADO ,COUNT(MCONCATENADO) AS QTD 
				FROM AUXILIAR_MENSAL_UNIQUE GROUP BY 1) AS B 
			WHERE A.MCONCATENADO = B.MCONCATENADO)) AS Percentual
FROM AUXILIAR_MENSAL_UNIQUE A
;QUIT;

%mend;

/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

%macro B2C_Aplica_Regra_Esforco_Mensal;

%mensagem(4.2. Aplicacao para modelo Mensal - Esforco);
PROC SQL;
CREATE TABLE RECUPERA_OP_MEN_MATU AS 
SELECT *
,CASE 
	WHEN data_base <= (SELECT MAX(data_base)-13 FROM RECUPERA_OPERACAO_DIARIO) 
	THEN "SIM" ELSE "NÃO" END AS MATURADO 
FROM (
	SELECT * FROM RECUPERA_OPERACAO_DIARIO 
	WHERE data_base <= (SELECT MAX(data_base) 
						FROM RECUPERA_OPERACAO_DIARIO WHERE DIVIDA_DEPOIS > 0)) AS A 
ORDER BY data_base
;QUIT;


PROC SQL;
CREATE TABLE AUXILIAR_MENSAL AS 
SELECT 
SAFRA 
,MCONCATENADO
,USERNAME 
,SUM(POSSUI_DIVIDA) AS POSSUI_DIVIDA
,SUM(DIVIDA_PAGA) / SUM(POSSUI_DIVIDA) AS PERC_DIV
FROM RECUPERA_OP_MEN_MATU A 
GROUP BY 1,2,3
;QUIT;

PROC SORT DATA= AUXILIAR_MENSAL; BY MCONCATENADO DESCENDING PERC_DIV;

DATA AUXILIAR_MENSAL;
SET AUXILIAR_MENSAL;
BY MCONCATENADO;
IF first.MCONCATENADO then Posicao = 1;
ELSE Posicao + 1;
RUN;

PROC SQL;
CREATE TABLE TAS_MENSAL AS 
SELECT 
SAFRA 
,MCONCATENADO
,USERNAME
,CATX('',USERNAME,MCONCATENADO) AS ID
,POSSUI_DIVIDA
,Posicao	
,(Posicao/(SELECT QTD 
			FROM (
				SELECT MCONCATENADO ,COUNT(MCONCATENADO) AS QTD 
				FROM AUXILIAR_MENSAL GROUP BY 1) AS B 
			WHERE A.MCONCATENADO = B.MCONCATENADO)) AS Percentual
FROM AUXILIAR_MENSAL A
;QUIT;

%mend;

/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------*/

%macro B2C_Agrupa_Sumariza_Tabelas;

%mensagem(5. Sumariza tabelas);

%mensagem(5.1.1 Sumariza tabelas Unique Dia);

PROC SQL;
CREATE TABLE TB_COB_REC_DIARIO_UNIQUE AS SELECT 
A.SAFRA 
,data_base
,MES
,DIA
,A.USERNAME
,A.GRUPO_ATENDIMENTO
,CARTEIRA_ENTRADA
,FORNECEDOR 
,PRODUTO_FINAL
,SEGMENTACAO_FUTURA
,CLASS
,MATURADO
,CASE 	WHEN Percentual <=0.25 	THEN "1Q"		WHEN Percentual <=0.5 	THEN "2Q"
		WHEN Percentual <=0.75 	THEN "3Q"		ELSE "4Q" END AS QUARTIL
,"DIARIO" AS ESTRUTURA
,"UNIQUE" AS Abertura
,'B2C' AS TP_CLIENTE
,COUNT(DOCUMENTO) 	AS QTD_CONTRATO
,COUNT(CHAMADA) 	AS CHAMADA
,SUM(TMA) 			AS TEMPO_TMA
,SUM(ACORDOS) 		AS ACORDOS
,SUM(QUEBRAS) 		AS QUEBRAS
,SUM(DIVIDA_ANTES) 	AS DIVIDA_ANTES
,SUM(DIVIDA_DEPOIS) AS DIVIDA_DEPOIS
,SUM(DIVIDA_ANTES_S_RED) AS DIVIDA_ANTES_S_RED
,SUM(DIVIDA_DEPOIS_S_RED) AS DIVIDA_DEPOIS_S_RED 
,SUM(A.POSSUI_DIVIDA) 	AS POSSUI_DIVIDA
,SUM(DIVIDA_PAGA) 		AS DIVIDA_PAGA
,SUM(DIVIDA_NAO_PAGA) 	AS DIVIDA_NAO_PAGA
,SUM(DIVIDA_REDUZIDA) 	AS DIVIDA_REDUZIDA
,SUM(AGING_REDUZIDO) 	AS AGING_REDUZIDO
FROM RECUPERA_OP_DIA_MATU_UNIQUE A 
LEFT JOIN TAS_DIARIO_UNIQUE B ON A.DCONCATENADO = B.DCONCATENADO AND A.USERNAME = B.USERNAME
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
;QUIT;

%mensagem(5.1.2 Sumariza tabelas Unique Mes);
PROC SQL;
CREATE TABLE TB_COB_REC_MENSAL_UNIQUE AS SELECT 
A.SAFRA 
,data_base
,MES
,DIA
,A.USERNAME
,A.GRUPO_ATENDIMENTO
,CARTEIRA_ENTRADA
,FORNECEDOR 
,PRODUTO_FINAL
,SEGMENTACAO_FUTURA
,CLASS
,MATURADO
,CASE 	WHEN Percentual <=0.25 	THEN "1Q"		WHEN Percentual <=0.5 	THEN "2Q"
		WHEN Percentual <=0.75 	THEN "3Q"		ELSE "4Q" END AS QUARTIL
,"MENSAL" AS ESTRUTURA
,"UNIQUE" AS Abertura
,'B2C' AS TP_CLIENTE
,COUNT(DOCUMENTO) 	AS QTD_CONTRATO
,COUNT(CHAMADA) 	AS CHAMADA
,SUM(TMA) 			AS TEMPO_TMA
,SUM(ACORDOS) 		AS ACORDOS
,SUM(QUEBRAS) 		AS QUEBRAS
,SUM(DIVIDA_ANTES) 	AS DIVIDA_ANTES
,SUM(DIVIDA_DEPOIS) AS DIVIDA_DEPOIS
,SUM(DIVIDA_ANTES_S_RED) AS DIVIDA_ANTES_S_RED
,SUM(DIVIDA_DEPOIS_S_RED) AS DIVIDA_DEPOIS_S_RED 
,SUM(A.POSSUI_DIVIDA) 	AS POSSUI_DIVIDA
,SUM(DIVIDA_PAGA) 		AS DIVIDA_PAGA
,SUM(DIVIDA_NAO_PAGA) 	AS DIVIDA_NAO_PAGA
,SUM(DIVIDA_REDUZIDA) 	AS DIVIDA_REDUZIDA
,SUM(AGING_REDUZIDO) 	AS AGING_REDUZIDO
FROM RECUPERA_OP_MEN_MATU_UNIQUE A 
LEFT JOIN TAS_MENSAL_UNIQUE B ON A.MCONCATENADO = B.MCONCATENADO AND A.USERNAME = B.USERNAME
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
;QUIT;

%mensagem(5.2.1 Sumariza tabelas Esforco Dia);
PROC SQL;
CREATE TABLE TB_COB_REC_DIARIO_ESFORCO AS SELECT 
A.SAFRA 
,data_base
,MES
,DIA
,A.USERNAME
,A.GRUPO_ATENDIMENTO
,CARTEIRA_ENTRADA
,FORNECEDOR 
,PRODUTO_FINAL
,SEGMENTACAO_FUTURA
,CLASS
,MATURADO
,CASE 	WHEN Percentual <=0.25 	THEN "1Q"		WHEN Percentual <=0.5 	THEN "2Q"
		WHEN Percentual <=0.75 	THEN "3Q"		ELSE "4Q" END AS QUARTIL
,"DIARIO" AS ESTRUTURA
,"ESFORÇO" AS Abertura
,'B2C' AS TP_CLIENTE
,COUNT(DOCUMENTO) 	AS QTD_CONTRATO
,COUNT(CHAMADA) 	AS CHAMADA
,SUM(TMA) 			AS TEMPO_TMA
,SUM(ACORDOS) 		AS ACORDOS
,SUM(QUEBRAS) 		AS QUEBRAS
,SUM(DIVIDA_ANTES) 	AS DIVIDA_ANTES
,SUM(DIVIDA_DEPOIS) AS DIVIDA_DEPOIS
,SUM(DIVIDA_ANTES_S_RED) AS DIVIDA_ANTES_S_RED
,SUM(DIVIDA_DEPOIS_S_RED) AS DIVIDA_DEPOIS_S_RED 
,SUM(A.POSSUI_DIVIDA) 	AS POSSUI_DIVIDA
,SUM(DIVIDA_PAGA) 		AS DIVIDA_PAGA
,SUM(DIVIDA_NAO_PAGA) 	AS DIVIDA_NAO_PAGA
,SUM(DIVIDA_REDUZIDA) 	AS DIVIDA_REDUZIDA
,SUM(AGING_REDUZIDO) 	AS AGING_REDUZIDO
FROM RECUPERA_OP_DIA_MATU A 
LEFT JOIN TAS_DIARIO B ON A.DCONCATENADO = B.DCONCATENADO AND A.USERNAME = B.USERNAME
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
;QUIT;

%mensagem(5.2.2 Sumariza tabelas Esforco Mes);
PROC SQL;
CREATE TABLE TB_COB_REC_MENSAL_ESFORCO AS SELECT 
A.SAFRA 
,data_base
,MES
,DIA
,A.USERNAME
,A.GRUPO_ATENDIMENTO
,CARTEIRA_ENTRADA
,FORNECEDOR 
,PRODUTO_FINAL
,SEGMENTACAO_FUTURA
,CLASS
,MATURADO
,CASE 	WHEN Percentual <=0.25 	THEN "1Q"		WHEN Percentual <=0.5 	THEN "2Q"
		WHEN Percentual <=0.75 	THEN "3Q"		ELSE "4Q" END AS QUARTIL
,"MENSAL" AS ESTRUTURA
,"ESFORÇO" AS Abertura
,'B2C' AS TP_CLIENTE
,COUNT(DOCUMENTO) 	AS QTD_CONTRATO
,COUNT(CHAMADA) 	AS CHAMADA
,SUM(TMA) 			AS TEMPO_TMA
,SUM(ACORDOS) 		AS ACORDOS
,SUM(QUEBRAS) 		AS QUEBRAS
,SUM(DIVIDA_ANTES) 	AS DIVIDA_ANTES
,SUM(DIVIDA_DEPOIS) AS DIVIDA_DEPOIS
,SUM(DIVIDA_ANTES_S_RED) AS DIVIDA_ANTES_S_RED
,SUM(DIVIDA_DEPOIS_S_RED) AS DIVIDA_DEPOIS_S_RED 
,SUM(A.POSSUI_DIVIDA) 	AS POSSUI_DIVIDA
,SUM(DIVIDA_PAGA) 		AS DIVIDA_PAGA
,SUM(DIVIDA_NAO_PAGA) 	AS DIVIDA_NAO_PAGA
,SUM(DIVIDA_REDUZIDA) 	AS DIVIDA_REDUZIDA
,SUM(AGING_REDUZIDO) 	AS AGING_REDUZIDO
FROM RECUPERA_OP_MEN_MATU A
LEFT JOIN TAS_MENSAL B ON A.MCONCATENADO = B.MCONCATENADO AND A.USERNAME = B.USERNAME
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
;QUIT;

%mend;


%macro B2C_Consolida_UniqueEsforco;

%mensagem(6. Consolida dados);

%mensagem(6.1 Consolida Unique - Mes/Dia e Esforço - Mes/Dia);
DATA
	WORK.TB_REC_CONSOLIDADO_2M_B2C;
SET 
TB_COB_REC_MENSAL_ESFORCO
TB_COB_REC_MENSAL_UNIQUE
TB_COB_REC_DIARIO_ESFORCO
TB_COB_REC_DIARIO_UNIQUE
;
RUN;

PROC SQL;
CREATE TABLE TB_USERNAME AS
SELECT 
SAFRA
, GRUPO_ATENDIMENTO 
, QUARTIL
, ESTRUTURA
, ABERTURA
, COUNT(DISTINCT USERNAME) AS DISTINCT_USERNAME
FROM TB_REC_CONSOLIDADO_2M_B2C
GROUP BY 1,2,3,4,5
ORDER BY 4 DESC,5 ASC,1,2,3
;QUIT;

%mensagem(6.2 Sumariza dados Consolidados);
PROC SQL;
CREATE TABLE WORK.TB_ANALISE_RECEPTIVO_SM_B2C AS
SELECT 
A.SAFRA 
, data_base 
, MES 
, DIA 
, A.GRUPO_ATENDIMENTO 
, CARTEIRA_ENTRADA 
, FORNECEDOR 
, PRODUTO_FINAL 
, SEGMENTACAO_FUTURA 
, CLASS
, MATURADO 
, A.QUARTIL 
, A.ESTRUTURA 
, A.ABERTURA
, B.DISTINCT_USERNAME
, TP_CLIENTE
, 'PF' AS PESSOA
, SUM(QTD_CONTRATO) AS QTD_CONTRATO
, SUM(CHAMADA) AS CHAMADA
, SUM(TEMPO_TMA) AS TEMPO_TMA
, SUM(ACORDOS) AS ACORDOS
, SUM(QUEBRAS) AS QUEBRAS
, SUM(DIVIDA_ANTES) AS DIVIDA_ANTES
, SUM(DIVIDA_DEPOIS) AS DIVIDA_DEPOIS
, SUM(POSSUI_DIVIDA) AS POSSUI_DIVIDA
, SUM(DIVIDA_ANTES_S_RED) AS DIVIDA_ANTES_S_RED
, SUM(DIVIDA_DEPOIS_S_RED) AS DIVIDA_DEPOIS_S_RED 
, SUM(DIVIDA_PAGA) AS DIVIDA_PAGA
, SUM(DIVIDA_NAO_PAGA) AS DIVIDA_NAO_PAGA
, SUM(DIVIDA_REDUZIDA) AS DIVIDA_REDUZIDA
, SUM(AGING_REDUZIDO) AS AGING_REDUZIDO
, COUNT(*) AS QTD_USERNAME
FROM WORK.TB_REC_CONSOLIDADO_2M_B2C A
LEFT JOIN TB_USERNAME B 
ON A.SAFRA = B.SAFRA 
AND A.GRUPO_ATENDIMENTO = B.GRUPO_ATENDIMENTO 
AND A.QUARTIL = B.QUARTIL
AND A.ESTRUTURA = B.ESTRUTURA
AND A.ABERTURA = B.ABERTURA
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
;QUIT;

%mend;


%macro B2C_Regra_Data_consolidacao;

%mensagem(7. Regras para Tabela FINAL);

%mensagem(7.1 Define Data minima para BINDROWS);

PROC SQL noprint;
SELECT MIN(SAFRA) AS SAFRA_MIN
into :DT_MIN
FROM WORK.TB_ANALISE_RECEPTIVO_SM_B2C
;QUIT;

%PUT &DT_MIN.;

PROC SQL;
CREATE TABLE WORK.TB_B2C_ANALISE_RECEPTIVO AS
SELECT * FROM TEMP.TB_B2C_ANALISE_RECEPTIVO 
WHERE SAFRA < &DT_MIN.
;QUIT;

%mensagem(7.2 Define Data minima para BINDROWS);
DATA
	TEMP.TB_B2C_ANALISE_RECEPTIVO(WHERE=(SAFRA >=&partida_inicial.));
SET
WORK.TB_B2C_ANALISE_RECEPTIVO
WORK.TB_ANALISE_RECEPTIVO_SM_B2C
;RUN;

PROC SORT DATA= TEMP.TB_B2C_ANALISE_RECEPTIVO; BY ESTRUTURA Abertura data_base;

%mend;
